### ISSUE TITLE
Supports check

### ISSUE THREAD

**Issue by joppuyo** [joppuyo/large-small-dynamic-viewport-units-polyfill#5]
Don't run on devices that support new units

**Comment by joppuyo** [comment]
Fixed in v0.1.0

**Comment by Mr-SvaRoq** [comment]
Hi, 

I have v0.1.0 and its still not working on devices that support new units. When I was using dev tools, it couldnt fine variables. 
-Lenovo TB-X606F, Chrome v108

But another android device where I have Chrome v107, its run fine and in dev tools, I could see the variables. 
-Oukitel RT1, Chrome v107

If I am doing something wrong, let me know pls :)

EDIT: 
I hava tried it on iphone11, Chrome v108 and its works fine there. So I do not know, where is the problem,

**Comment by joppuyo** [comment]
I made a change so the polyfill does not run on devices that natively support the units. Because Android Chrome 108 supports these new units, it's expected that the polyfill does not run in this case.

Can you test that the element is sized properly in the new browsers? Like the readme says the following pattern should be used for elements where you want to use the new units:

```css
.my-dynamic-hero-element {
    width: 100%;
    height: 100vh; /* For browsers that don't support CSS variables */
    height: calc(var(--1dvh, 1vh) * 100); /* This is the "polyfill" */
    height: 100dvh; /* This is for future browsers that support svh, dvh and lvh viewport units */
}
```

When a device supports the new dvh unit, it will use the last height property in the list which means the polyfill is not required at all.

**Comment by joppuyo** [comment]
Also, can you share a screenshot of the correct behavior and the incorrect behavior?

**Comment by Mr-SvaRoq** [comment]
```
.sgt-app {
  //height: 100%;
  //height: 100svh;
  height: calc(var(--1svh, 1vh) * 100); /* This is the "polyfill" */
  display: flex;
  flex-direction: column;
}
```

Oukitel RT1, Chrome v107 (polyfill is working fine), sorry for bad quality, but I couldnt take a screenshot
![image](https://user-images.githubusercontent.com/38141247/207606745-f6f0c121-8431-43cd-9a0a-fea3a8c26646.png)

- Lenovo device,  Chrome v108, the app nav bar is behind android navbar
![image](https://user-images.githubusercontent.com/38141247/207607493-ea8f2b2e-9dd6-4262-8d7b-f02146ebced8.png)

in both case, using the same code (local development)

**Comment by joppuyo** [comment]
This is an issue with the implementation. You are not supposed to use the polyfill without native fallback as [described in the documentation](https://github.com/joppuyo/large-small-dynamic-viewport-units-polyfill#2-write-css). You should change the CSS to the following:

```css
.sgt-app {
  height: calc(var(--1svh, 1vh) * 100); /* This is the "polyfill" */
  height: 100svh;  /* This is for future browsers that support svh, dvh and lvh viewport units */
  display: flex;
  flex-direction: column;
}
```

If the code doesn't work even after this there could be a bug in the library.

**Comment by Mr-SvaRoq** [comment]
yep, that was my mistake,

 first my implamantaion was... so rookie mistake

```
.sgt-app {
  height: 100svh;  /* obviosly (now), its not working :D */
  height: calc(var(--1svh, 1vh) * 100); /* This is the "polyfill" */
  display: flex;
  flex-direction: column;
}
```

thanks for your help and time. 

PS: at least, u can add more devices on your test devices :D

**Comment by joppuyo** [comment]
Glad you were able to figure out the issue!

I will try to see if I can make the documentation more clear about this.
